name: Minio Tests
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  minio-tests:
    name: Minio Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        duckdb_version: [ '<submodule_version>' ]
    env:
      S3_TEST_SERVER_AVAILABLE: 1
      DUCKDB_S3_ENDPOINT: duckdb-minio.com:9000
      DUCKDB_S3_USE_SSL: false
      GEN: ninja
      VCPKG_TARGET_TRIPLET: x64-linux
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      DISABLE_UNITY: 1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Checkout DuckDB to version
        if: ${{ matrix.duckdb_version != '<submodule_version>'}}
        run: |
          cd duckdb
          git checkout ${{ matrix.duckdb_version }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install Ninja
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}
          save: ${{ github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb' }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: a42af01b72c28a8e1d7b48107b33e4f286a55ef6

      - name: Build
        shell: bash
        run: make debug

      - name: Start S3/HTTP test server
        shell: bash
        run: |
          cd duckdb
          sudo ./scripts/install_s3_test_server.sh
          source ./scripts/run_s3_test_server.sh
          sleep 30

      - name: Write AWS credentials file
        shell: bash
        run: |
          ./scripts/create_minio_credential_file.sh

      - name: Test
        shell: bash
        run: |
          make test_debug

      - name: Run Env tests
        shell: bash
        env:
          DUCKDB_AWS_TESTING_ENV_AVAILABLE: 1
          AWS_ACCESS_KEY_ID: duckdb_env_testing_id
          AWS_SECRET_ACCESS_KEY: duckdb_env_testing_key
          AWS_DEFAULT_REGION: duckdb_env_testing_region
        run: |
          ./build/debug/test/unittest "*/test/sql/env/*"